version: '3.9'

services:
  postgres:
    image: postgres
    container_name: "users_postgres"
    restart: always
    ports:
      - "5433:5433"
    env_file:
    - ".env"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: "users_app"
    container_name: "users_app"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
    - ".env"
    volumes:
      - ".:/app/"

volumes:
  postgres_data:
